/* This file was generated by SableCC (http://www.sablecc.org/). */

package lrc.node;

import java.util.*;
import lrc.analysis.*;

@SuppressWarnings("nls")
public final class ALrcFile extends PLrcFile
{
    private final LinkedList<PElement> _element_ = new LinkedList<PElement>();

    public ALrcFile()
    {
        // Constructor
    }

    public ALrcFile(
        @SuppressWarnings("hiding") List<?> _element_)
    {
        // Constructor
        setElement(_element_);

    }

    @Override
    public Object clone()
    {
        return new ALrcFile(
            cloneList(this._element_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALrcFile(this);
    }

    public LinkedList<PElement> getElement()
    {
        return this._element_;
    }

    public void setElement(List<?> list)
    {
        for(PElement e : this._element_)
        {
            e.parent(null);
        }
        this._element_.clear();

        for(Object obj_e : list)
        {
            PElement e = (PElement) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._element_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._element_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._element_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PElement> i = this._element_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PElement) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
