/* This file was generated by SableCC (http://www.sablecc.org/). */

package lrc.node;

import lrc.analysis.*;

@SuppressWarnings("nls")
public final class ATaggedLineElement extends PElement
{
    private TLBracket _lBracket_;
    private TBcontent _tag_;
    private TRBracket _rBracket_;
    private TBcontent _lyric_;

    public ATaggedLineElement()
    {
        // Constructor
    }

    public ATaggedLineElement(
        @SuppressWarnings("hiding") TLBracket _lBracket_,
        @SuppressWarnings("hiding") TBcontent _tag_,
        @SuppressWarnings("hiding") TRBracket _rBracket_,
        @SuppressWarnings("hiding") TBcontent _lyric_)
    {
        // Constructor
        setLBracket(_lBracket_);

        setTag(_tag_);

        setRBracket(_rBracket_);

        setLyric(_lyric_);

    }

    @Override
    public Object clone()
    {
        return new ATaggedLineElement(
            cloneNode(this._lBracket_),
            cloneNode(this._tag_),
            cloneNode(this._rBracket_),
            cloneNode(this._lyric_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATaggedLineElement(this);
    }

    public TLBracket getLBracket()
    {
        return this._lBracket_;
    }

    public void setLBracket(TLBracket node)
    {
        if(this._lBracket_ != null)
        {
            this._lBracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lBracket_ = node;
    }

    public TBcontent getTag()
    {
        return this._tag_;
    }

    public void setTag(TBcontent node)
    {
        if(this._tag_ != null)
        {
            this._tag_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tag_ = node;
    }

    public TRBracket getRBracket()
    {
        return this._rBracket_;
    }

    public void setRBracket(TRBracket node)
    {
        if(this._rBracket_ != null)
        {
            this._rBracket_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rBracket_ = node;
    }

    public TBcontent getLyric()
    {
        return this._lyric_;
    }

    public void setLyric(TBcontent node)
    {
        if(this._lyric_ != null)
        {
            this._lyric_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lyric_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._lBracket_)
            + toString(this._tag_)
            + toString(this._rBracket_)
            + toString(this._lyric_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._lBracket_ == child)
        {
            this._lBracket_ = null;
            return;
        }

        if(this._tag_ == child)
        {
            this._tag_ = null;
            return;
        }

        if(this._rBracket_ == child)
        {
            this._rBracket_ = null;
            return;
        }

        if(this._lyric_ == child)
        {
            this._lyric_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._lBracket_ == oldChild)
        {
            setLBracket((TLBracket) newChild);
            return;
        }

        if(this._tag_ == oldChild)
        {
            setTag((TBcontent) newChild);
            return;
        }

        if(this._rBracket_ == oldChild)
        {
            setRBracket((TRBracket) newChild);
            return;
        }

        if(this._lyric_ == oldChild)
        {
            setLyric((TBcontent) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
