/* This file was generated by SableCC (http://www.sablecc.org/). */

package lrc.node;

import lrc.analysis.*;

@SuppressWarnings("nls")
public final class TBcontent extends Token
{
    public TBcontent(String text)
    {
        setText(text);
    }

    public TBcontent(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TBcontent(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTBcontent(this);
    }
}
