/* This file was generated by SableCC (http://www.sablecc.org/). */

package lrc.analysis;

import lrc.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseALrcFile(ALrcFile node);
    void caseATagLineElement(ATagLineElement node);
    void caseATaggedLineElement(ATaggedLineElement node);

    void caseTLBracket(TLBracket node);
    void caseTRBracket(TRBracket node);
    void caseTBcontent(TBcontent node);
    void caseTBlank(TBlank node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
