/* This file was generated by SableCC (http://www.sablecc.org/). */

package lrc.analysis;

import java.util.*;
import lrc.node.*;

public class ReversedDepthFirstAdapter extends AnalysisAdapter
{
    public void inStart(Start node)
    {
        defaultIn(node);
    }

    public void outStart(Start node)
    {
        defaultOut(node);
    }

    public void defaultIn(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    public void defaultOut(@SuppressWarnings("unused") Node node)
    {
        // Do nothing
    }

    @Override
    public void caseStart(Start node)
    {
        inStart(node);
        node.getEOF().apply(this);
        node.getPLrcFile().apply(this);
        outStart(node);
    }

    public void inALrcFile(ALrcFile node)
    {
        defaultIn(node);
    }

    public void outALrcFile(ALrcFile node)
    {
        defaultOut(node);
    }

    @Override
    public void caseALrcFile(ALrcFile node)
    {
        inALrcFile(node);
        {
            List<PElement> copy = new ArrayList<PElement>(node.getElement());
            Collections.reverse(copy);
            for(PElement e : copy)
            {
                e.apply(this);
            }
        }
        outALrcFile(node);
    }

    public void inATagLineElement(ATagLineElement node)
    {
        defaultIn(node);
    }

    public void outATagLineElement(ATagLineElement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATagLineElement(ATagLineElement node)
    {
        inATagLineElement(node);
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        if(node.getBcontent() != null)
        {
            node.getBcontent().apply(this);
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        outATagLineElement(node);
    }

    public void inATaggedLineElement(ATaggedLineElement node)
    {
        defaultIn(node);
    }

    public void outATaggedLineElement(ATaggedLineElement node)
    {
        defaultOut(node);
    }

    @Override
    public void caseATaggedLineElement(ATaggedLineElement node)
    {
        inATaggedLineElement(node);
        if(node.getLyric() != null)
        {
            node.getLyric().apply(this);
        }
        if(node.getRBracket() != null)
        {
            node.getRBracket().apply(this);
        }
        if(node.getTag() != null)
        {
            node.getTag().apply(this);
        }
        if(node.getLBracket() != null)
        {
            node.getLBracket().apply(this);
        }
        outATaggedLineElement(node);
    }
}
