/* This file was generated by SableCC (http://www.sablecc.org/). */

package lrc.parser;

import lrc.node.*;
import lrc.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLBracket(@SuppressWarnings("unused") TLBracket node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRBracket(@SuppressWarnings("unused") TRBracket node)
    {
        this.index = 1;
    }

    @Override
    public void caseTBcontent(@SuppressWarnings("unused") TBcontent node)
    {
        this.index = 2;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 3;
    }
}
